import { auth, db } from './firebase-dev.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { addDoc, collection, doc, getDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const id=new URLSearchParams(location.search).get('id')||'',shell=document.getElementById('gear-detail'),status=document.getElementById('gear-detail-status');let listing=null,currentUser=null;
const by=id=>document.getElementById(id);const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(value||0));const millis=stamp=>stamp?.toMillis?.()||stamp?.seconds*1000||0;
function render(){if(!listing)return;document.title=`${listing.title} | BANDtroductions Gear Exchange`;by('detail-image').src=listing.imageUrl;by('detail-image').alt=listing.title;by('detail-category').textContent=listing.category||'Music Gear';by('detail-title').textContent=listing.title;by('detail-price').textContent=money(listing.price);by('detail-condition').textContent=listing.condition;by('detail-location').textContent=`📍 ${[listing.city,listing.state].filter(Boolean).join(', ')}`;by('detail-sale-type').textContent=listing.saleType||'For Sale';by('detail-description').textContent=listing.description||'';by('detail-seller').textContent=listing.sellerName||'BANDtroductions Member';by('detail-date').textContent=listing.createdAt?.toDate?`Listed ${listing.createdAt.toDate().toLocaleDateString()}`:'';const featured=listing.featured===true&&(!listing.featuredUntil||millis(listing.featuredUntil)>Date.now());by('detail-badge').hidden=!featured;by('detail-sold').hidden=listing.status!=='sold';if(listing.pickupNotes){by('detail-pickup').hidden=false;by('detail-pickup').textContent=`Pickup / meeting: ${listing.pickupNotes}`;}if(listing.videoUrl){by('detail-video').hidden=false;by('detail-video').href=listing.videoUrl;}const message=by('detail-message');message.href=currentUser?`messages.html?to=${encodeURIComponent(listing.sellerId||'')}`:`login.html?returnTo=${encodeURIComponent(location.pathname+location.search)}`;message.textContent=listing.status==='sold'?'ITEM SOLD':currentUser?.uid===listing.sellerId?'YOUR LISTING':'MESSAGE SELLER';if(listing.status==='sold'||currentUser?.uid===listing.sellerId){message.removeAttribute('href');message.style.opacity='.55';message.style.pointerEvents='none';}shell.hidden=false;status.hidden=true;}
by('detail-share').addEventListener('click',async()=>{const data={title:listing?.title||'Gear Exchange',text:`${listing?.title||'Music gear'} on BANDtroductions Gear Exchange`,url:location.href};if(navigator.share){try{await navigator.share(data)}catch(error){if(error?.name!=='AbortError')console.error(error)}}else{await navigator.clipboard.writeText(location.href);alert('Listing link copied.');}});
by('detail-report').addEventListener('click',async()=>{if(!listing)return;if(!currentUser){location.href=`login.html?returnTo=${encodeURIComponent(location.pathname+location.search)}`;return}const reason=prompt('Briefly tell us what is wrong with this listing:');if(!reason?.trim())return;try{await addDoc(collection(db,'gearReports'),{listingId:id,listingTitle:listing.title,reporterId:currentUser.uid,reason:reason.trim().slice(0,1000),status:'open',createdAt:serverTimestamp()});alert('Thank you. The listing has been reported for review.');}catch(error){console.error(error);alert('The report could not be submitted.');}});
onAuthStateChanged(auth,user=>{currentUser=user;render();});
if(!id){status.textContent='Listing not found.';}else getDoc(doc(db,'gearListings',id)).then(snapshot=>{if(!snapshot.exists()||snapshot.data().published===false){status.textContent='This listing is no longer available.';return}listing={id:snapshot.id,...snapshot.data()};render();}).catch(error=>{console.error(error);status.textContent=error?.code==='permission-denied'?'Gear Exchange permissions need to be enabled.':'This listing could not be loaded.';});
